# Add namespace to all resources
namespace: common-namespace

# Add annotations to all resources
commonAnnotations:
  newCommonAnnotation: common-annotation

# Add labels to all resources
commonLabels:
  newCommonLabel: common-label

# List all source resources here. These will not be changed
resources:
- nginx-deployment.yaml

configMapGenerator:
- name: nginx-configmap
  files:
    - nginx-config.txt

secretGenerator:
- name: env_file_secret
  env: env.txt
  type: Opaque
# vars:
#   - name: WORDPRESS_SERVICE
#     objref:
#       kind: Service
#       name: wordpress
#       apiVersion: v1
#   - name: MYSQL_SERVICE
#     objref:
#       kind: Service
#       name: mysql
#       apiVersion: v1

