# Add namespace to all resources
namespace: common-namespace

# Add annotations to all resources
commonAnnotations:
  newCommonAnnotation: common-annotation

# Add labels to all resources
commonLabels:
  newCommonLabel: common-label

# List all source resources here. These will not be changed
resources:
- nginx-deployment.yaml

# Create a Config Map from a combination of values in a file and literals
configMapGenerator:
- name: nginx-configmap
  files:
    - nginx-config.txt
  literals:	
    - from-literal=true
- name: nginx-configmap-env
  env: env.txt

# Create a Secret resource
secretGenerator:
- name: env-file-secret
  env: env.txt 
  type: Opaque
- name: certificate-secret
  files:
    - certificate.txt 
- name: literal-secrets
  literals:
    - password=literal-password
    - host=liternal-host

# See https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml
vars:
  - name: MY_SERVICE_NAME
    objref:
      kind: ConfigMap
      name: nginx-configmap-env
      apiVersion: v1
    fieldref:
        fieldpath: data.host