# Prepend this on all resource names
namePrefix: dev-

# Patch the partial resource definitions into the base
patchesStrategicMerge:
- replica-count-dev.yaml

# Merge values from development.properties in the existing Config Map
configMapGenerator:
- name: example-configmap
  behavior: merge
  files:
  - env.properties

bases:
- ../../base